# Generated by Django 4.0.4 on 2022-06-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField()),
                ('nombreProducto', models.CharField(max_length=40)),
                ('precioProducto', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='items_carro')),
            ],
            options={
                'db_table': 'db_items_carro',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('codigo_seg', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_seg', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'db_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('username_sus', models.CharField(default='none', max_length=20, primary_key=True, serialize=False)),
                ('estado_sus', models.BooleanField()),
            ],
            options={
                'db_table': 'db_suscripcion',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_venta',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('codigo_seg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seguimiento')),
            ],
            options={
                'db_table': 'db_historial',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'db_carrito',
            },
        ),
    ]
